-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Circuit.

module AbsCircuit where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

newtype Circuit = Circuit [Conn]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Conn = Conn Gate Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Gate
    = PureG Exp
    | AndG Exp Ident
    | OrG Ident Ident
    | RShiftG Ident Integer
    | LShiftG Ident Integer
    | NotG Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp = IdentExp Ident | NumExp Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

