-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelCircuit where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsCircuit

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsCircuit.Ident -> Result
transIdent x = case x of
  AbsCircuit.Ident string -> failure x

transCircuit :: AbsCircuit.Circuit -> Result
transCircuit x = case x of
  AbsCircuit.Circuit conns -> failure x

transConn :: AbsCircuit.Conn -> Result
transConn x = case x of
  AbsCircuit.Conn gate ident -> failure x

transGate :: AbsCircuit.Gate -> Result
transGate x = case x of
  AbsCircuit.PureG exp -> failure x
  AbsCircuit.AndG exp ident -> failure x
  AbsCircuit.OrG ident1 ident2 -> failure x
  AbsCircuit.RShiftG ident integer -> failure x
  AbsCircuit.LShiftG ident integer -> failure x
  AbsCircuit.NotG ident -> failure x

transExp :: AbsCircuit.Exp -> Result
transExp x = case x of
  AbsCircuit.IdentExp ident -> failure x
  AbsCircuit.NumExp integer -> failure x
